'use client';
import { useCallback, useEffect, useState } from 'react';
import AdminStatusBadge from '../components/AdminStatusBadge';
import styles from './orders.module.css';
const money = new Intl.NumberFormat('en-IE', { style: 'currency', currency: 'EUR' });
const orderStatuses = ['new', 'processing', 'ready', 'completed', 'cancelled'], paymentStatuses = ['pending', 'unpaid', 'paid'];
const paymentLabels = { bank_transfer: 'Bank transfer', cash_on_pickup: 'Cash on pickup' };
export default function OrdersManager() {
  const [orders, setOrders] = useState([]), [status, setStatus] = useState('loading'), [error, setError] = useState(''), [open, setOpen] = useState(null), [saving, setSaving] = useState(null);
  const load = useCallback(async () => { setStatus('loading'); setError(''); try { const response = await fetch('/shop/api/admin/orders', { cache: 'no-store' }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setOrders(result.orders); setStatus('ready'); } catch (loadError) { setError(loadError.message || 'Unable to load orders.'); setStatus('error'); } }, []);
  useEffect(() => { queueMicrotask(load); }, [load]);
  async function update(id, change) { setSaving(id); setError(''); try { const response = await fetch(`/shop/api/admin/orders/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(change) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setOrders((current) => current.map((order) => order.id === id ? result.order : order)); } catch (updateError) { setError(updateError.message || 'Unable to update order.'); } finally { setSaving(null); } }
  if (status === 'loading') return <p className={styles.state} role="status">Loading orders…</p>;
  if (status === 'error') return <div className={styles.state} role="alert"><p>{error}</p><button type="button" onClick={load}>Retry</button></div>;
  if (!orders.length) return <p className={styles.state}>No orders yet.</p>;
  return <div className={styles.manager}>{error ? <p className={styles.error} role="alert">{error}</p> : null}<div className={styles.tableWrap}><table><thead><tr><th>Reference</th><th>Date</th><th>Customer</th><th>Pickup</th><th>Payment</th><th>Status</th><th>Total</th><th /></tr></thead><tbody>{orders.map((order) => <tr key={order.id}><td><code>{order.id.slice(0, 8)}</code></td><td>{order.createdAt ? new Date(order.createdAt).toLocaleString('en-GB') : '—'}</td><td>{order.customer.name}<small>{order.customer.email}</small></td><td>{order.pickupLocation.name}</td><td>{paymentLabels[order.paymentMethod]}<small>{order.paymentStatus}</small></td><td><AdminStatusBadge status={order.orderStatus} /></td><td>{money.format(order.totalCents / 100)}</td><td><button type="button" onClick={() => setOpen(open === order.id ? null : order.id)}>{open === order.id ? 'Close' : 'Open'}</button></td></tr>)}</tbody></table></div>{orders.map((order) => open === order.id ? <section className={styles.detail} key={`${order.id}-detail`}><div className={styles.detailHead}><div><h2>Order {order.id}</h2><p>{order.customer.name} · {order.customer.email} · {order.customer.phone}</p>{order.customer.company ? <p>{order.customer.company.name} · {order.customer.company.registrationNumber || 'No registration number'} · {order.customer.company.vatNumber || 'No VAT number'}</p> : null}<p>{order.pickupLocation.name}, {order.pickupLocation.address}</p></div><div className={styles.controls}><label>Order status<select disabled={saving === order.id || order.orderStatus === 'cancelled'} value={order.orderStatus} onChange={(e) => update(order.id, { orderStatus: e.target.value })}>{orderStatuses.map((value) => <option key={value} value={value}>{value}</option>)}</select></label><label>Payment status<select disabled={saving === order.id} value={order.paymentStatus} onChange={(e) => update(order.id, { paymentStatus: e.target.value })}>{paymentStatuses.map((value) => <option key={value} value={value}>{value}</option>)}</select></label></div></div><table><thead><tr><th>SKU</th><th>Product</th><th>Qty</th><th>Unit price</th><th>Line total</th></tr></thead><tbody>{order.items.map((item) => <tr key={item.productId}><td>{item.sku ?? '—'}</td><td>{item.name}</td><td>{item.quantity}</td><td>{money.format(item.unitPriceCents / 100)}</td><td>{money.format(item.lineTotalCents / 100)}</td></tr>)}</tbody><tfoot><tr><th colSpan="4">Total</th><th>{money.format(order.totalCents / 100)}</th></tr></tfoot></table>{saving === order.id ? <p role="status">Saving…</p> : null}{order.stockRestoredAt ? <p>Stock restored {new Date(order.stockRestoredAt).toLocaleString('en-GB')}</p> : null}</section> : null)}</div>;
}
