import test from 'node:test'; import assert from 'node:assert/strict';
import { assertActorMayManageTarget, partnerDecisionUpdate, validateAdministrativeRoleTransition, validateCompany, validateDiscountPercent, validateProfileName } from '../lib/auth/userModel.mjs';
const active=(role,extra={})=>({uid:role,role,status:'active',partnerStatus:'none',...extra});
test('ordinary profile and company edits are allowlisted and normalized',()=>{assert.equal(validateProfileName(' Jane '),'Jane');assert.deepEqual(validateCompany({name:' ACME ',phone:' 123 ',ignored:'x'}),{name:'ACME',registrationNumber:'',vatNumber:'',phone:'123',billingAddress:''});});
test('approval and rejection preserve the documented role invariants',()=>{assert.deepEqual(partnerDecisionUpdate(true),{role:'partner',partnerStatus:'approved'});assert.deepEqual(partnerDecisionUpdate(false),{role:'customer',partnerStatus:'rejected',discountPercent:0});});
test('discount validation supports decimals from zero through one hundred',()=>{assert.equal(validateDiscountPercent(12.5),12.5);assert.throws(()=>validateDiscountPercent(-1));assert.throws(()=>validateDiscountPercent(101));});
test('staff may manage customers and partners but not staff or administrators',()=>{const staff=active('staff');assert.equal(assertActorMayManageTarget(staff,active('customer')),undefined);assert.equal(assertActorMayManageTarget(staff,active('partner',{partnerStatus:'approved'})),undefined);assert.throws(()=>assertActorMayManageTarget(staff,active('staff')));assert.throws(()=>assertActorMayManageTarget(staff,active('admin')));});
test('only active administrators can assign administrative roles',()=>{const admin=active('admin'),customer=active('customer');assert.equal(validateAdministrativeRoleTransition(admin,customer,'staff'),'staff');assert.throws(()=>validateAdministrativeRoleTransition(active('staff'),customer,'admin'));assert.throws(()=>validateAdministrativeRoleTransition({...admin,status:'disabled'},customer,'staff'));});
test('wholesale states cannot be bypassed through administrative role changes',()=>{const admin=active('admin');assert.throws(()=>validateAdministrativeRoleTransition(admin,active('customer',{partnerStatus:'pending'}),'staff'));assert.throws(()=>validateAdministrativeRoleTransition(admin,active('partner',{partnerStatus:'approved'}),'customer'));});
