'use client';
/* eslint-disable @next/next/no-img-element -- blob URLs are temporary local upload previews. */
import { useCallback, useEffect, useRef, useState } from 'react';
import { DndContext, KeyboardSensor, PointerSensor, closestCenter, useSensor, useSensors } from '@dnd-kit/core';
import { SortableContext, arrayMove, rectSortingStrategy, sortableKeyboardCoordinates, useSortable } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import ProductImage from '../../components/ProductImage';
import { centsToEuros, validateProductInput } from '../../../lib/adminProductValidation.mjs';
import { ADMIN_PRODUCTS_PAGE_SIZE, deriveAdminProducts, getAdminDeviceFilterOptions, getAdminProductsPage } from '../../../lib/adminProductCatalog.mjs';
import { deriveCompatibilitySelection, getCompatibilityEditorOptions } from '../../../lib/adminProductCompatibility.mjs';
import AdminPageHeader from '../components/AdminPageHeader'; import AdminAccordionRow from '../components/AdminAccordionRow'; import AdminButton from '../components/AdminButton'; import AdminCombobox from '../components/AdminCombobox'; import AdminEditorActions from '../components/AdminEditorActions'; import AdminFeedback from '../components/AdminFeedback'; import { AdminFormSection, AdminNumberInput, AdminSelect, AdminTextarea, AdminTextInput } from '../components/AdminForm'; import AdminStatusBadge from '../components/AdminStatusBadge'; import ConfirmationDialog from '../components/ConfirmationDialog'; import useAdminEditorAccordion from '../components/useAdminEditorAccordion'; import useConfirmationDialog from '../components/useConfirmationDialog'; import styles from './products.module.css';
const ENDPOINT='/shop/api/admin/products', RESERVE_ENDPOINT=`${ENDPOINT}/reserve-id`, IMAGE_ENDPOINT='/shop/api/admin/product-images';
const SORTS=new Set(['default','nameAsc','nameDesc','priceAsc','priceDesc','newest','oldest']); const DEFAULT_QUERY={search:'',productType:'',brand:'',series:'',model:'',sort:'default',page:1};
const money=(c)=>c==null?'—':new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR'}).format(c/100); const date=(v)=>v?new Intl.DateTimeFormat('en-GB',{dateStyle:'medium'}).format(new Date(v)):'—';
const storedImage=(path,index)=>({kind:'stored',key:`stored:${index}:${path}`,path});
const draftOf=(p={})=>({id:p.id||'',sku:p.sku??null,name:p.name||'',slug:p.slug||'',description:p.description||'',status:p.status||'active',productTypeId:p.productTypeId||'',purchasePrice:centsToEuros(p.purchasePriceCents),wholesalePrice:centsToEuros(p.wholesalePriceCents),retailPrice:centsToEuros(p.retailPriceCents),stockQty:p.stockQty??0,modelIds:[...(p.modelIds||[])],imageItems:(p.imagePaths||[]).map(storedImage),metaTitle:p.metaTitle||'',metaDescription:p.metaDescription||'',metaTitleManual:p.metaTitleManual===true,metaDescriptionManual:p.metaDescriptionManual===true,createdAt:p.createdAt||null,updatedAt:p.updatedAt||null});
const revokePending=(items=[])=>items.filter(item=>item.kind==='pending').forEach(item=>URL.revokeObjectURL(item.previewUrl));
async function request(url,options){const response=await fetch(url,{...options,headers:options?.body instanceof FormData?options.headers:{'Content-Type':'application/json',...options?.headers}}),body=await response.json();if(!response.ok)throw new Error(body.error||'Request failed.');return body;}
function queryString(query){const p=new URLSearchParams();for(const key of ['search','productType','brand','series','model','sort'])if(query[key]&&!(key==='sort'&&query[key]==='default'))p.set(key,query[key]);if(query.page>1)p.set('page',query.page);return p;}
function uploadPendingImage(productId,item,onProgress){return new Promise((resolve,reject)=>{const form=new FormData(),xhr=new XMLHttpRequest();form.append('file',item.file);form.append('productId',productId);xhr.open('POST',IMAGE_ENDPOINT);xhr.upload.onprogress=event=>{if(event.lengthComputable)onProgress(Math.round(event.loaded/event.total*100));};xhr.onload=()=>{try{const body=JSON.parse(xhr.responseText);if(xhr.status<200||xhr.status>=300)throw new Error(body.error||'Upload failed.');resolve(body.path);}catch(error){reject(error);}};xhr.onerror=()=>reject(new Error('Upload failed.'));xhr.send(form);});}
export default function ProductsManager({initialQuery}){
 const[query,setQuery]=useState({...DEFAULT_QUERY,...initialQuery,sort:SORTS.has(initialQuery.sort)?initialQuery.sort:'default'}),[catalog,setCatalog]=useState({products:[],productTypes:[],devices:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[draft,setDraft]=useState(null),[saving,setSaving]=useState(false),[feedback,setFeedback]=useState(null),[seoOpen,setSeoOpen]=useState(false); const draftRef=useRef(null),confirmation=useConfirmationDialog();
 const confirmDiscard=useCallback(()=>confirmation.confirm({title:'Discard unsaved changes?',description:'Your product changes will be lost.',confirmLabel:'Discard',destructive:true}),[confirmation]); const accordion=useAdminEditorAccordion({confirmDiscard});
 const load=useCallback(async()=>{try{setCatalog(await request(ENDPOINT));setError('');}catch{setError('Unable to load products.');}finally{setLoading(false);}},[]); useEffect(()=>{request(ENDPOINT).then(setCatalog).catch(()=>setError('Unable to load products.')).finally(()=>setLoading(false));},[]); useEffect(()=>{const p=queryString(query);window.history.replaceState(null,'',`${window.location.pathname}${p.size?`?${p}`:''}`);},[query]); useEffect(()=>{draftRef.current=draft;},[draft]); useEffect(()=>()=>revokePending(draftRef.current?.imageItems),[]);
 const filtered=deriveAdminProducts(catalog.products,query,catalog.productTypes),pages=Math.max(1,Math.ceil(filtered.length/ADMIN_PRODUCTS_PAGE_SIZE)),current=Math.min(query.page,pages),shown=getAdminProductsPage(filtered,current),types=new Map(catalog.productTypes.map(t=>[t.id,t.name])),devices=new Map(catalog.devices.map(d=>[d.id,d]));
 async function cleanup(paths){let failed=0;for(const path of [...new Set(paths)]){try{await request(IMAGE_ENDPOINT,{method:'DELETE',body:JSON.stringify({path})});}catch(error){failed+=1;console.error(`Unable to clean product image ${path}.`,error);}}return failed;}
 async function open(product){const id=product?.id||'new-product',closing=accordion.openId===id,ok=closing?await accordion.closeEditor():await accordion.openEditor(id);if(ok){revokePending(draft?.imageItems);setDraft(closing?null:draftOf(product));setSeoOpen(false);}}
 function change(field,value){setDraft(c=>{const next={...c,[field]:value};if(!c.id&&field==='name'&&!c.slug)next.slug=value.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');return next;});accordion.setDirty(true);setFeedback(null);}
 async function changeQuery(changes){if(accordion.isDirty&&!await confirmDiscard())return;if(accordion.openId){accordion.markSaved();await accordion.closeEditor();revokePending(draft?.imageItems);setDraft(null);}setQuery(c=>({...c,...changes,page:Object.hasOwn(changes,'page')?changes.page:1}));}
 async function save(product){if(saving)return;setFeedback(null);const storedPaths=draft.imageItems.filter(item=>item.kind==='stored').map(item=>item.path);try{validateProductInput({...draft,imagePaths:storedPaths});}catch(error){setFeedback({tone:'error',text:error.message});return;}setSaving(true);const uploaded=[];try{const productId=product?.id||(await request(RESERVE_ENDPOINT,{method:'POST',body:JSON.stringify({})})).id;const resolved=new Map();for(const item of draft.imageItems.filter(image=>image.kind==='pending')){const path=await uploadPendingImage(productId,item,progress=>setDraft(current=>({...current,imageItems:current.imageItems.map(image=>image.key===item.key?{...image,progress}:image)})));uploaded.push(path);resolved.set(item.key,path);}const imagePaths=draft.imageItems.map(item=>item.kind==='stored'?item.path:resolved.get(item.key));const payload={...draft,id:product?undefined:productId,imagePaths,expectedUpdatedAt:product?.updatedAt};delete payload.imageItems;delete payload.sku;delete payload.createdAt;delete payload.updatedAt;if(product)delete payload.id;const body=await request(product?`${ENDPOINT}/${encodeURIComponent(product.id)}`:ENDPOINT,{method:product?'PATCH':'POST',body:JSON.stringify(payload)});const removed=(product?.imagePaths||[]).filter(path=>!imagePaths.includes(path)),cleanupFailed=await cleanup(removed);revokePending(draft.imageItems);setCatalog(c=>({...c,products:product?c.products.map(p=>p.id===product.id?body.product:p):[...c.products,body.product]}));accordion.markSaved();setDraft(draftOf(body.product));if(!product)await accordion.openEditor(body.product.id);setFeedback({tone:cleanupFailed?'error':'success',text:cleanupFailed?`Product saved, but ${cleanupFailed} removed image${cleanupFailed===1?'':'s'} could not be deleted from Storage.`:'Product saved.'});}catch(error){const cleanupFailed=await cleanup(uploaded);setDraft(current=>current?{...current,imageItems:current.imageItems.map(item=>item.kind==='pending'?{...item,progress:0}:item)}:current);setFeedback({tone:'error',text:`${error.message}${cleanupFailed?' Some uploaded images could not be cleaned up.':''}`});}finally{setSaving(false);}}
 async function remove(product){if(!await confirmation.confirm({title:'Delete product?',description:'The product and its unreferenced images will be removed. Its SKU will never be reused.',confirmLabel:'Delete Product',destructive:true}))return;setSaving(true);try{const body=await request(`${ENDPOINT}/${encodeURIComponent(product.id)}`,{method:'DELETE'});setCatalog(c=>({...c,products:c.products.filter(p=>p.id!==product.id)}));accordion.markSaved();await accordion.closeEditor();revokePending(draft?.imageItems);setDraft(null);setFeedback({tone:body.cleanupFailed?'error':'success',text:body.cleanupFailed?`Product deleted, but ${body.cleanupFailed} image${body.cleanupFailed===1?'':'s'} could not be removed from Storage.`:'Product deleted.'});}catch(e){setFeedback({tone:'error',text:e.message});}finally{setSaving(false);}}
 function selectFiles(files){if(saving)return;const accepted=[],rejected=[];for(const file of files){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size<=0||file.size>5*1024*1024){rejected.push(file);continue;}accepted.push({kind:'pending',key:crypto.randomUUID(),file,previewUrl:URL.createObjectURL(file),progress:0});}if(accepted.length){setDraft(current=>({...current,imageItems:[...current.imageItems,...accepted]}));accordion.setDirty(true);}setFeedback(rejected.length?{tone:'error',text:'Upload a JPEG, PNG, or WebP image no larger than 5 MB.'}:null);}
 return <section className={styles.manager}><AdminPageHeader title="Products" description={loading?'Loading products…':`${shown.length} of ${filtered.length} products`} actions={<AdminButton variant="primary" disabled={loading} onClick={()=>void open(null)}>Add Product</AdminButton>}/><Filters query={query} catalog={catalog} loading={loading} change={changeQuery}/>{feedback?<AdminFeedback tone={feedback.tone}>{feedback.text}</AdminFeedback>:null}{error?<div className={styles.error}><p>{error}</p><AdminButton size="small" onClick={()=>{setLoading(true);void load();}}>Retry</AdminButton></div>:null}{loading?<div className={styles.loading}>Loading products…</div>:null}
 {!loading&&!error?<div className={styles.productList}>{accordion.openId==='new-product'?<AdminAccordionRow id="new-product" expanded onToggle={()=>void open(null)} summary={<strong>New Product</strong>}><Editor draft={draft} catalog={catalog} seoOpen={seoOpen} setSeoOpen={setSeoOpen} change={change} save={()=>save(null)} cancel={()=>open(null)} selectFiles={selectFiles} saving={saving}/></AdminAccordionRow>:null}{shown.map(product=><AdminAccordionRow key={product.id} id={`product-${product.id}`} expanded={accordion.openId===product.id} onToggle={()=>void open(product)} summary={<Summary product={product} type={types.get(product.productTypeId)} devices={devices}/>}><Editor draft={draft} catalog={catalog} seoOpen={seoOpen} setSeoOpen={setSeoOpen} change={change} save={()=>save(product)} cancel={()=>open(product)} remove={()=>remove(product)} selectFiles={selectFiles} saving={saving}/></AdminAccordionRow>)}{!shown.length&&accordion.openId!=='new-product'?<div className={styles.empty}>No products match the current filters.</div>:null}</div>:null}
 {!loading&&!error&&shown.length?<nav className={styles.pagination}><AdminButton size="small" disabled={current===1} onClick={()=>void changeQuery({page:current-1})}>Previous</AdminButton><span>Page {current} of {pages}</span><AdminButton size="small" disabled={current===pages} onClick={()=>void changeQuery({page:current+1})}>Next</AdminButton></nav>:null}<ConfirmationDialog {...confirmation.dialogProps}/></section>;
}
function Summary({product,type,devices}){const names=product.modelIds.slice(0,2).map(id=>devices.get(id)?.name||id);return <div className={styles.productSummary}><div className={styles.thumbnail}><ProductImage imagePath={product.imagePaths[0]} productName={product.name}/></div><span className={styles.productIdentity}><strong>{product.name}</strong><small>SKU {product.sku} · {type||'No type'}{names.length?` · ${names.join(', ')}${product.modelIds.length>2?` +${product.modelIds.length-2}`:''}`:''}</small></span><span className={styles.priceGrid}><small>Purchase {money(product.purchasePriceCents)}</small><small>Wholesale {money(product.wholesalePriceCents)}</small><small>Retail {money(product.retailPriceCents)}</small></span><span>{product.stockQty} in stock</span><AdminStatusBadge status={product.status}/></div>}
function Editor({draft,catalog,seoOpen,setSeoOpen,change,save,cancel,remove,selectFiles,saving}){if(!draft)return null;return <form onSubmit={e=>{e.preventDefault();void save();}}><AdminFormSection title="Basic Information"><AdminTextInput id="product-name" label="Name" required value={draft.name} onChange={e=>change('name',e.target.value)}/><AdminTextInput id="product-slug" label="Slug" required value={draft.slug} onChange={e=>change('slug',e.target.value)}/><Read label="Product ID" value={draft.id||'Generated when saved'}/><Read label="SKU" value={draft.sku??'Allocated when saved'}/><AdminSelect id="product-status" label="Status" value={draft.status} onChange={e=>change('status',e.target.value)}><option value="active">Active</option><option value="inactive">Inactive</option></AdminSelect><AdminTextarea id="product-description" label="Description" value={draft.description} onChange={e=>change('description',e.target.value)}/></AdminFormSection><AdminFormSection title="Classification and Compatibility"><AdminSelect id="product-type" label="Product Type" required value={draft.productTypeId} onChange={e=>change('productTypeId',e.target.value)}><option value="">Select type</option>{catalog.productTypes.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</AdminSelect><Compatibility draft={draft} devices={catalog.devices} change={change}/></AdminFormSection><AdminFormSection title="Pricing and Inventory"><AdminTextInput id="purchase-price" label="Purchase Price (€)" inputMode="decimal" value={draft.purchasePrice} onChange={e=>change('purchasePrice',e.target.value)}/><AdminTextInput id="wholesale-price" label="Wholesale Price (€)" inputMode="decimal" value={draft.wholesalePrice} onChange={e=>change('wholesalePrice',e.target.value)}/><AdminTextInput id="retail-price" label="Retail Price (€)" inputMode="decimal" value={draft.retailPrice} onChange={e=>change('retailPrice',e.target.value)}/><AdminNumberInput id="stock" label="Stock quantity" min="0" step="1" value={draft.stockQty} onChange={e=>change('stockQty',e.target.value)}/></AdminFormSection><AdminFormSection title="Images"><Images draft={draft} change={change} selectFiles={selectFiles}/></AdminFormSection><section className={styles.seo}><button type="button" aria-expanded={seoOpen} onClick={()=>setSeoOpen(v=>!v)}>SEO <span>{seoOpen?'▾':'▸'}</span></button>{seoOpen?<div className={styles.seoFields}><AdminTextInput id="meta-title" label="Meta Title" value={draft.metaTitle} onChange={e=>{change('metaTitle',e.target.value);change('metaTitleManual',true);}}/><AdminTextarea id="meta-description" label="Meta Description" value={draft.metaDescription} onChange={e=>{change('metaDescription',e.target.value);change('metaDescriptionManual',true);}}/></div>:null}</section><p className={styles.timestamps}>Created {date(draft.createdAt)} · Updated {date(draft.updatedAt)}</p><AdminEditorActions onSave={save} onCancel={cancel} onDelete={remove} deleteLabel="Delete Product" saving={saving}/></form>}
function Compatibility({draft,devices,change}){
 const initial=deriveCompatibilitySelection(draft.modelIds,devices),[brandId,setBrandId]=useState(initial.brandId),[seriesId,setSeriesId]=useState(initial.seriesId),byId=new Map(devices.map(d=>[d.id,d])),options=getCompatibilityEditorOptions(devices,brandId,seriesId,draft.modelIds),availableModels=options.models.filter(model=>!draft.modelIds.includes(model.id)),invalid=draft.modelIds.filter(id=>byId.get(id)?.type!=='model'),crossSeries=seriesId?draft.modelIds.filter(id=>{const model=byId.get(id);return model?.type==='model'&&model.parentId!==seriesId;}):[];
 function selectBrand(id){if(id===brandId)return;setBrandId(id);setSeriesId('');change('modelIds',[]);}
 function selectSeries(id){if(id===seriesId)return;setSeriesId(id);change('modelIds',[]);}
 function addModel(id){if(id&&!draft.modelIds.includes(id))change('modelIds',[...draft.modelIds,id]);}
 function removeModel(id){change('modelIds',draft.modelIds.filter(modelId=>modelId!==id));}
 return <div className={styles.compatibilityEditor}>
  <AdminCombobox id="compatibility-brand" label="Brand" options={options.brands} value={brandId} onChange={selectBrand} placeholder="Search or select brand…"/>
  <AdminCombobox id="compatibility-series" label="Series" options={options.series} value={seriesId} onChange={selectSeries} disabled={!brandId} placeholder={brandId?'Search or select series…':'Select brand first…'}/>
  <AdminCombobox id="compatibility-model" label="Model" options={availableModels} value="" onChange={addModel} clearable={false} disabled={!seriesId} placeholder={seriesId?'Search or select model…':'Select series first…'} emptyMessage={draft.modelIds.length?'All matching models are selected.':'No matching models.'}/>
  {draft.modelIds.length?<div className={styles.selectedModels} aria-label="Selected compatible models">{draft.modelIds.map(id=><button type="button" key={id} onClick={()=>removeModel(id)} aria-label={`Remove ${byId.get(id)?.name||id}`}>{byId.get(id)?.name||id} <span aria-hidden="true">×</span></button>)}</div>:null}
  {crossSeries.length?<AdminFeedback tone="error">Models span multiple Series: {crossSeries.map(id=>byId.get(id)?.name||id).join(', ')}. Choose a Brand or Series to clear incompatible selections.</AdminFeedback>:null}
  {invalid.length?<AdminFeedback tone="error">Invalid legacy references: {invalid.join(', ')}. Remove or correct them before saving.</AdminFeedback>:null}
 </div>;
}
function SortableImage({item,index,name,remove}){const{attributes,listeners,setNodeRef,transform,transition,isDragging}=useSortable({id:item.key});return <div ref={setNodeRef} style={{transform:CSS.Transform.toString(transform),transition}} className={`${styles.imageCard} ${isDragging?styles.imageDragging:''}`}><div className={styles.imagePreview}>{item.kind==='pending'?<img src={item.previewUrl} alt="Pending upload preview"/>:<ProductImage imagePath={item.path} productName={name}/>}</div>{item.kind==='pending'&&item.progress?<progress max="100" value={item.progress}>{item.progress}%</progress>:null}<div className={styles.imageFooter}><span className={styles.imageBadges}>{index===0?<span className={styles.primaryBadge}>Primary</span>:null}{item.kind==='pending'?<span className={styles.pendingBadge}>{item.progress?`Uploading ${item.progress}%`:'Pending'}</span>:null}</span><button type="button" className={styles.imageDragHandle} aria-label={`Reorder image ${index+1}`} {...attributes} {...listeners}>⋮⋮</button><button type="button" className={styles.imageRemove} onClick={()=>remove(item)} aria-label={`Remove image ${index+1}`}>Remove</button></div></div>}
function Images({draft,change,selectFiles}){const[dragOver,setDragOver]=useState(false),inputRef=useRef(null),dragDepth=useRef(0),sensors=useSensors(useSensor(PointerSensor,{activationConstraint:{distance:6}}),useSensor(KeyboardSensor,{coordinateGetter:sortableKeyboardCoordinates}));function remove(item){if(item.kind==='pending')URL.revokeObjectURL(item.previewUrl);change('imageItems',draft.imageItems.filter(image=>image.key!==item.key));}function dragEnd({active,over}){if(!over||active.id===over.id)return;const oldIndex=draft.imageItems.findIndex(item=>item.key===active.id),newIndex=draft.imageItems.findIndex(item=>item.key===over.id);if(oldIndex>=0&&newIndex>=0)change('imageItems',arrayMove(draft.imageItems,oldIndex,newIndex));}function enter(event){event.preventDefault();dragDepth.current+=1;if([...event.dataTransfer.items].some(item=>item.kind==='file'))setDragOver(true);}function leave(event){event.preventDefault();dragDepth.current=Math.max(0,dragDepth.current-1);if(!dragDepth.current)setDragOver(false);}function drop(event){event.preventDefault();dragDepth.current=0;setDragOver(false);selectFiles([...event.dataTransfer.files]);}return <div className={styles.images}><DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={dragEnd}><SortableContext items={draft.imageItems.map(item=>item.key)} strategy={rectSortingStrategy}>{draft.imageItems.map((item,index)=><SortableImage key={item.key} item={item} index={index} name={draft.name} remove={remove}/>)}</SortableContext></DndContext><div className={`${styles.upload} ${dragOver?styles.uploadActive:''}`} onDragEnter={enter} onDragOver={event=>{event.preventDefault();event.dataTransfer.dropEffect='copy';}} onDragLeave={leave} onDrop={drop} aria-label="Add product images by dropping files here or choosing files"><span>Drop images here</span><small>or</small><button type="button" onClick={()=>inputRef.current?.click()}>Choose files</button><input ref={inputRef} className={styles.visuallyHidden} type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={event=>{selectFiles([...event.target.files]);event.target.value='';}}/></div></div>}
function Read({label,value}){return <div className={styles.readField}><span>{label}</span><strong>{value}</strong></div>}
function Filters({query,catalog,loading,change}){const{brands,series,models}=getAdminDeviceFilterOptions(catalog.devices,query.brand,query.series);return <div className={styles.controls}><label className={styles.searchField}><span>Search</span><input value={query.search} disabled={loading} onChange={e=>void change({search:e.target.value})}/></label><div className={styles.filterGrid}><AdminCombobox id="filter-brand" label="Brand" options={brands} value={query.brand} disabled={loading} placeholder="Search or select brand…" onChange={v=>void change({brand:v,series:'',model:''})}/><AdminCombobox id="filter-series" label="Series" options={series} value={query.series} disabled={loading||!query.brand} placeholder={query.brand?'Search or select series…':'Select brand first…'} onChange={v=>void change({series:v,model:''})}/><AdminCombobox id="filter-model" label="Model" options={models} value={query.model} disabled={loading||!query.series} placeholder={query.series?'Search or select model…':'Select series first…'} onChange={v=>void change({model:v})}/><Select label="Product Type" value={query.productType} options={catalog.productTypes} change={v=>change({productType:v})}/><label><span>Sort</span><select value={query.sort} disabled={loading} onChange={e=>void change({sort:e.target.value})}><option value="default">Default</option><option value="nameAsc">Name A–Z</option><option value="nameDesc">Name Z–A</option><option value="priceAsc">Purchase price low–high</option><option value="priceDesc">Purchase price high–low</option><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select></label></div></div>}
function Select({label,value,options,change}){return <label><span>{label}</span><select value={value} onChange={e=>void change(e.target.value)}><option value="">All</option>{options.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>}
