'use client';
import Link from 'next/link';
import { useEffect, useRef } from 'react';
import ProductImage from '../ProductImage';
import { useCart } from './CartContext';
import styles from './CartDrawer.module.css';
const money = new Intl.NumberFormat('en-IE', { style: 'currency', currency: 'EUR' });
const unavailable = { missing_product: 'Product no longer available', inactive: 'Product no longer available', missing_price: 'Price unavailable', out_of_stock: 'Out of stock' };
export default function CartDrawer() {
  const { items, lines, totalCents, valid, status, error, isOpen, closeCart, removeItem, increment, decrement, resolve } = useCart();
  const closeButton = useRef(null), previousFocus = useRef(null);
  useEffect(() => { if (!isOpen) return undefined; resolve(); previousFocus.current = document.activeElement; const body = document.body, scrollY = window.scrollY, previous = { overflow: body.style.overflow, position: body.style.position, top: body.style.top, width: body.style.width }; Object.assign(body.style, { overflow: 'hidden', position: 'fixed', top: `-${scrollY}px`, width: '100%' }); closeButton.current?.focus(); const onKeyDown = (event) => { if (event.key === 'Escape') closeCart(); }; document.addEventListener('keydown', onKeyDown); return () => { document.removeEventListener('keydown', onKeyDown); Object.assign(body.style, previous); window.scrollTo(0, scrollY); previousFocus.current?.focus?.(); }; }, [isOpen, closeCart, resolve]);
  if (!isOpen) return null;
  return <div className={styles.backdrop} onMouseDown={(event) => { if (event.target === event.currentTarget) closeCart(); }}><aside className={styles.drawer} id="shop-cart-drawer" role="dialog" aria-modal="true" aria-labelledby="cart-title"><header><h2 id="cart-title">Cart</h2><button ref={closeButton} type="button" onClick={closeCart} aria-label="Close cart">×</button></header><div className={styles.content}>
    {!items.length ? <div className={styles.empty}><span aria-hidden="true">□</span><h3>Your cart is empty</h3><p>Products you add will appear here.</p><button type="button" onClick={closeCart}>Continue shopping</button></div> : null}
    {status === 'loading' && items.length ? <p role="status">Refreshing cart…</p> : null}{error ? <p className={styles.error} role="alert">{error} <button type="button" onClick={() => resolve()}>Retry</button></p> : null}
    <div className={styles.lines}>{lines.map((line) => <article className={styles.line} key={line.productId}><div className={styles.thumb}><ProductImage imagePath={line.primaryImagePath} productName={line.name} /></div><div className={styles.lineBody}><Link href={`/product/${line.slug}`} onClick={closeCart}><strong>{line.name}</strong></Link>{line.sku !== null ? <small>SKU {line.sku}</small> : null}<span>{line.applicableUnitPriceCents === null ? 'Price unavailable' : money.format(line.applicableUnitPriceCents / 100)}</span>{!line.purchasable ? <p className={styles.unavailable}>{line.unavailableReason === 'insufficient_stock' ? `Only ${line.stockQty} available` : unavailable[line.unavailableReason]}</p> : null}<div className={styles.lineActions}><div><button type="button" aria-label={`Decrease ${line.name} quantity`} disabled={line.quantity <= 1} onClick={() => decrement(line.productId)}>−</button><span>{line.quantity}</span><button type="button" aria-label={`Increase ${line.name} quantity`} disabled={line.quantity >= line.stockQty} onClick={() => increment(line.productId)}>+</button></div><button type="button" onClick={() => removeItem(line.productId)}>Remove</button><strong>{line.lineTotalCents === null ? '—' : money.format(line.lineTotalCents / 100)}</strong></div></div></article>)}</div>
  </div><footer><div><span>Total</span><strong>{money.format(totalCents / 100)}</strong></div>{valid && items.length ? <Link className={styles.checkout} href="/checkout" onClick={closeCart}>Proceed to checkout</Link> : <button type="button" disabled>{status === 'loading' ? 'Checking cart…' : 'Proceed to checkout'}</button>}</footer></aside></div>;
}
